language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t mateusaueressig/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mateusaueressig/react-test npm test -- --coverage

after_success:
  - docker build -t mateusaueressig/multi-client ./client
  - docker build -t mateusaueressig/multi-nginx ./nginx
  - docker build -t mateusaueressig/multi-server ./server
  - docker build -t mateusaueressig/multi-worker ./worker
  # log in to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-sdtin
  # push images to dockerhub
  - docker push mateusaueressig/multi-client
  - docker push mateusaueressig/multi-nginx
  - docker push mateusaueressig/multi-server
  - docker push mateusaueressig/multi-worker
